export const message = {
  submit: "SUBMIT",
  create: "CREATE",
  forgotpassword: "Forgot Password?",
  welcomeback: "Welcome back!",
  enteryouremail: "Please enter your email address",
  donthaveaccount: "Don't have an account?",
  createAccount: "Create Account",
  signinfbtwitter: "Sign up from Facebook & Twitter",
  facebook: "Facebook",
  twitter: "Twitter",
  chooseAccountType: "Choose your account type",
  doandverify:
    "Create new customers for your business by seamlessly offering rewards for litter removal",
  listyouraccess:
    "Collect & Verify litter to earn discounts on your favorite purchases",
  createanaccount: "Create an account",
  pleaseenterdetails: "Please enter your personal details",
  allreadyhaveanaccount: "Already have an account?",
  signin: "Sign in",
  forgotpassword2: "Forgot Password",
  forgotpasswordtext2:
    "Please enter your email address, you’ll get a link to reset your password.",
  collectionCompleted: "Filter Collections",
  myFriends: "My Friends",
  logout: "Logout",
  changepassword: "Change Password",
  currentLocation: "Current Location",
  otpverification: "Verification Code",
  otpverification2:
    "Please enter your 6 digital verification code to change your password.",
  aboutUs: "About Us",
  contactUs: "Contact Us",
  termspolicy: "Terms & Policies",
  item: "SINGLE ITEMS",
  small: "SMALL BAG",
  large: "LARGE BAG",
  startHunt: "START HUNT",
  completeHunt: "COMPLETE HUNT",
  underVaerification: "Under Verification",
  signupVerifyDetails:
    "Thank you for joining Trash2Cash, a verification email will be sent to you soon.",
  businessProfile: "Business Profile",
  businessProfileDetails: "Please enter your business details",
  consumer: "Consumer",
  business: "Business",
  deleteMedia: "Delete Media",
  startHunt: "START HUNT",
  new: "New",
  verified: "Verified",
  verify: "VERIFY",
  voucher: "Vouchers",
  createHotspot: "Create Trash Hotspot",
  hunters: "Hunters",
  rewardTitle: "Your 2X rewards are waiting",
  rewardContent:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras non rhoncus sapien. Aenean euismod congue lorem.",
  okButton: "OK",
  send: "SEND",
  enterVoucherCode: "Enter voucher code...",
  voucherTitle: "Voucher",
  voucherCode: "Voucher Code - ",
  going: "GOING",
  createVoucher: "Create Voucher",
  editVoucher: "Edit Voucher",
  employee: "Employee",
  voucherTitlePlaceholder: "Voucher Title",
  pointsRequired: "Point Required",
  from: "From",
  to: "To",
  voucherBusiness: "Vouchers From Other Business",
  offerPerUser: "Offer Per User (Optional)",
  offerAvailable: "Offer Available Interval",
  saveProfile: "SAVE PROFILE",
  editProfile: "Edit Profile",
  editBusinessProfile: "Edit Business Profile",
  editHotspot: "Edit Trash Hotspot",
  updateHotspot: "UPDATE TRASH HOTSPOT",
  voucher: "Vouchers",
};
