import { StyleSheet, Platform } from "react-native";

// Third Party
import { widthPercentageToDP as wp } from "react-native-responsive-screen";

// Constants
import { font } from "../../../constant/font";
import { colors } from "../../../constant/colors";
import { fontSize } from "../../../constant/fontSize";

export const styles = StyleSheet.create({
    container: { flex: 1 },
    marketImageView: { flex: 4 },
    marketImage: { width: "100%", height: "100%" },
    marketDetailView: {
        flex: 6,
        borderTopLeftRadius: wp("8%"),
        borderTopRightRadius: wp("8%"),
        backgroundColor: colors.white,
        marginTop: wp(-12),
    },
    marketNameView: {
        flexDirection: "row",
    },
    directionColumn: { flexDirection: "column" },
    marketNameText: {},
    voucherItemContainer: {
        flexDirection: "row",
        marginVertical: wp("3%"),
        padding: wp("4%"),
        borderRadius: wp("4%"),
        backgroundColor: colors.white,
        shadowColor: Platform.OS === "android" ? "#4C4C55" : "#0000000D",
        shadowOffset: { width: 5, height: 3 },
        shadowOpacity: 0.4,
        elevation: 5,
    },
    locationView: {
        flexDirection: "row",
        paddingTop: wp("1%"),
    },
    pendingView: {
        flexDirection: "row",
        alignItems: "center",
    },
    locationIcon: {
        width: wp("5%"),
        height: wp("5%"),
        marginRight: wp("1%"),
        paddingTop: wp("8%"),
    },
    descriptionView: { marginTop: wp("5%"), alignItems: "center" },
    pendingIcon: {
        width: wp("6%"),
        height: wp("6%"),
        resizeMode: "contain",
        marginRight: wp("2%"),
    },
    marketNameLeftView: { flex: 1.5 },
    marketNameRightView: {
        alignItems: "flex-end",
        flex: 1,
    },
    marketNameRightView2: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "flex-end",
    },
    reviewTag: {
        backgroundColor: "rgba(253, 122, 21,0.2)",
        paddingVertical: wp("2%"),
        paddingHorizontal: wp("2%"),
        borderTopLeftRadius: wp("1%"),
        borderTopRightRadius: wp("4%"),
        borderBottomRightRadius: wp("1%"),
        borderBottomLeftRadius: wp("4%"),
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    voucherButtonStyle: {
        paddingVertical: wp("2%"),
        width: wp("20%"),
        borderRadius: wp("4%"),
        alignItems: "center",
        justifyContent: "center",
    },
    reviewButton: { paddingVertical: wp("2%"), alignItems: "center" },
    marketNameText: {
        fontSize: fontSize?.f24,
        color: colors.black,
        fontFamily: font.bold,
    },
    locationText: {
        fontSize: fontSize?.f15,
        color: colors.black,
        fontFamily: font.medium,
    },
    marketDescriptionText: {
        fontSize: fontSize?.f14,
        color: colors.black,
        fontFamily: font.regular,
        textAlign: "left",
    },
    reviewText: {
        fontSize: fontSize?.f12,
        color: colors.orange1,
        fontFamily: font.medium,
    },
    reviewTextView: {
        textDecorationLine: "underline",
        fontSize: fontSize?.f12,
        textAlign: "center",
        color: colors?.logout,
        fontFamily: font?.medium,
        letterSpacin: 0.25,
    },
    starIcon: {
        width: wp("5%"),
        height: wp("5%"),
        resizeMode: "contain",
        marginRight: wp("2%"),
    },
    timeText: {
        fontSize: fontSize?.f14,
        color: colors.black,
        fontFamily: font.light,
        marginTop: wp("1%"),
        width: wp("45%"),
    },
    pointView: {
        flexDirection: "row",
        alignContent: "center",
        justifyContent: "flex-end",
        marginLeft: 20,
    },
    pointsText: {
        fontSize: fontSize?.f16,
        color: colors.black,
        fontFamily: font.semiBold,
    },
    pointsText1: { textAlign: "right", marginLeft: 5, alignSelf: "center" },
    voucherText: {
        fontSize: fontSize?.f17,
        color: colors.logout,
        fontFamily: font.bold,
        textAlignVertical: "top",
        marginTop: wp("1%"),
    },
    voucherHeaderComponent: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: wp("9%"),
        marginBottom: wp("1%"),
        alignItems: "center",
    },
    voucherListStyle: {
        marginVertical: wp("8%"),
        paddingHorizontal: wp("5%"),
    },
    voucherShareIcon: {
        width: wp("7%"),
        height: wp("7%"),
        resizeMode: "contain",
    },
    voucherDeleteIcon: {
        width: wp("7%"),
        height: wp("7%"),
        resizeMode: "contain",
        marginRight: wp("3%"),
    },
    modalImageBackground: { flex: 1 },
    modalStyle: { flex: 1, justifyContent: "flex-end" },
    horizontalLine: {
        width: wp("20%"),
        borderRadius: wp("5%"),
        backgroundColor: colors.grey1,
        height: wp("1.5%"),
        alignSelf: "center",
        marginVertical: wp("3%"),
    },
    modalContainer: {
        bottom: 0,
        backgroundColor: colors.white,
        borderTopLeftRadius: wp("9%"),
        borderTopRightRadius: wp("9%"),
        width: wp("100%"),
        alignSelf: "center",
        marginBottom: -wp("4.5%"),
    },
    offerImage: {
        height: wp("25%"),
        width: wp("25%"),
        alignSelf: "center",
        marginVertical: wp("6%"),
    },
    rewardView: { paddingVertical: wp("6%") },
    redeemTitle: {
        fontSize: fontSize?.f24,
        color: colors.black,
        fontFamily: font.bold,
        width: "85%",
        textAlign: "center",
    },
    redeemTitle2: {
        fontSize: fontSize?.f16,
        textAlign: "center",
        color: colors.grey,
        marginHorizontal: wp("3%"),
        fontFamily: font.semiBoldItalic,
    },
    codeBarView: {
        height: wp("17%"),
        width: wp("80%"),
        alignItems: "center",
        justifyContent: "center",
        marginVertical: wp("3%"),
    },
    codeBarText: {
        fontSize: fontSize?.f20,
        color: colors.white,
        fontFamily: font.semiBold,
    },
    shareButton: {
        width: wp("90%"),
        borderRadius: wp("9%"),
        borderColor: "#386874",
        borderWidth: 2,
        paddingVertical: wp("4%"),
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: colors.white,
        alignSelf: "center",
        marginVertical: wp("3%"),
    },
    shareButtonText: {
        fontSize: fontSize?.f17,
        color: "#386874",
        fontFamily: font.semiBold,
    },
    redeemView: {
        alignItems: "center",
    },
    shareWithText: {
        fontSize: fontSize?.f24,
        color: colors.black,
        fontFamily: font.bold,
    },
    socialButtonMainView: {
        width: wp("80%"),
        alignSelf: "center",
        marginTop: wp("5%"),
        justifyContent: "space-between",
        alignItems: "center",
        flexDirection: "row",
    },
    socialButtontouch1: { justifyContent: "center", alignItems: "center" },
    socialButtontouch2: { justifyContent: "center", alignItems: "center" },
    socialIconTouch: { width: wp("14%"), height: wp("14%") },
    socialIconTouch1: { width: wp("15%"), height: wp("15%") },
    shareView: { alignItems: "center" },
    buyContent: {
        fontSize: fontSize?.f20,
        color: colors.black,
        fontFamily: font.bold,
        textAlign: "center",
        paddingVertical: wp("8%"),
    },
    rateText: {
        fontSize: fontSize?.f20,
        color: colors.black,
        fontFamily: font.bold,
        textAlign: "center",
        marginTop: wp("6%"),
    },
    buyView: {
        alignItems: "center",
        paddingHorizontal: wp("12%"),
        paddingTop: wp("1%"),
    },
    cancelButton: {
        height: wp("15%"),
        width: wp("40%"),
        alignItems: "center",
        justifyContent: "center",
        borderRadius: wp("8%"),
        backgroundColor: "#D6D6D6",
        marginRight: wp("2%"),
    },
    buyButton: {
        height: wp("15%"),
        width: wp("40%"),
        alignItems: "center",
        justifyContent: "center",
        borderRadius: wp("8%"),
        marginLeft: wp("2%"),
    },
    cancelText: {
        fontSize: fontSize?.f22,
        color: colors.black,
        fontFamily: font.medium,
    },
    buyText: {
        fontSize: fontSize?.f22,
        color: colors.black,
        fontFamily: font.medium,
    },
    buyButtonView: { flexDirection: "row", marginVertical: wp("3%") },
    starContainerStyle: {
        width: wp("45%"),
        justifyContent: "space-between",
        marginVertical: wp("3%"),
    },
    provideReviewView: { marginHorizontal: wp("7%"), marginVertical: wp("3%") },
    reviewTextInput: {
        width: "100%",
        backgroundColor: colors.white,
        borderRadius: wp("4%"),
        height: wp("25%"),
        padding: wp("4%"),
        fontSize: fontSize?.f14,
        fontFamily: font?.semiBold,
        shadowColor: colors["grey-500"],
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        elevation: 4,
        textAlignVertical: "top",
    },
    limitView: {
        alignSelf: "flex-end",
        justifyContent: "flex-end",
        alignItems: "flex-end",
        marginRight: wp("3%"),
        marginBottom: wp("3%"),
        marginVertical: wp("2%"),
    },
    limitTextView: {
        color: "#0191B4",
        font: font?.regular,
        fontSize: fontSize?.f14,
    },
    submitButtonView: { marginVertical: wp("4%") },
    rewardImage: { height: wp("25%"), width: wp("25%") },
    loaderView: { flex: 1, justifyContent: "center", alignItems: "center" },
});